name: Docker Image CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:

  build:

    runs-on: euleros-2.10.1

    steps:
    - name: Build the Docker image
      uses: checkout-action@0.0.1
      with:
        ref: dev
    - run: cd repo_workspace && ls
    - run: echo ' ================== flag1 ================== '